version: "2.0"

services:

  kong:
    build:
      context: ./kong
      args:
        build_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        build_SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
    environment:
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PLUGINS: request-transformer,cors,key-auth,http-log
    ports:
      - ${KONG_PORT}:8000
      - ${KONG_PORT_TLS}:8443
    expose:
      - 8000
      - 8443

  auth:
    image: supabase/gotrue:latest
    ports:
      - ${AUTH_PORT}:9999
    depends_on:
      - db
    restart: always
    environment:
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_API_HOST: 0.0.0.0
      PORT: 9999
      GOTRUE_SITE_URL: localhost
      GOTRUE_MAILER_AUTOCONFIRM: 'true'
      GOTRUE_LOG_LEVEL: DEBUG
      GOTRUE_OPERATOR_TOKEN: ${OPERATOR_TOKEN}
      DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres?sslmode=disable'
    expose:
      - 9999

  rest:
    image: postgrest/postgrest:nightly-2021-03-05-19-03-d3a8b5f
    ports:
      - ${REST_PORT}:3000
    depends_on:
      - db
    restart: always
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
    expose:
      - 3000

  realtime:
    image: supabase/realtime:latest
    ports:
      - ${REALTIME_PORT}:4000
    depends_on:
      - db
    restart: on-failure
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: 5432
      PORT: 4000
      HOSTNAME: localhost
      # Disable JWT Auth locally. The JWT_SECRET will be ignored.
      SECURE_CHANNELS: 'false'
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - 4000

  db:
    image: mock-supabase-db:latest
    build:
      context: ./postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    expose:
      - 5432
